site_name: BLUE TEAM LABS
site_url: https://blueteamlabs.io/
repo_url: https://github.com/blueteamboss/blueteamlabs.io
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: cyan
  font:
    text: Arial
    code: JetBrains Mono
  logo: https://www.blueteamlabs.io/assets/logo.png
  favicon: https://www.blueteamlabs.io/assets/favicon.svg
nav:
  - index.md
  - blog/index.md
  - Lab Architecture:
    - arch/index.md
    - arch/network-security.md
    - arch/virtualization.md
  - resources.md
  - about.md
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.blocks.caption:
      prepend: true
plugins:
  - blog:
      blog_toc: true
      pagination: true
      post_excerpt: required
      pagination_per_page: 10
      archive_date_format: MMMM yyyy
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
